# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install --ignore-scripts

# Copy source code and other necessary files
COPY . .

# Build the project
RUN npm run build

# Expose port if needed (optional)
# EXPOSE 3000

# Command to run the MCP server
CMD [ "node", "build/index.js" ]
